### ISSUE TITLE
Hi, I founded little bug

### ISSUE THREAD

**Issue by songwritersg** [gccloud/parser#2]
i am not good at English sorry.
thanks for wonderful code.

i found little bug on i use set_delimiters();
line 532 on MY_Parser.php 
`if ( ! in_array($u[0], array('{else}','{break}','{default}'))) {`
i changed
`if ( ! in_array($u[0], array( $this->l_delim.'else'.$this->r_delim, $this->l_delim.'break'.$this->r_delim,$this->l_delim.'default'.$this->r_delim))) {`

**Comment by gccloud** [comment]
Hi !
Thanks for reporting that, that's a little bug indeed. I'll manage to correct it soon.

Have a nice day !
